In [2]:
def my_function():
    pass

In [3]:
def my_sq(x):
    return x ** 2

In [4]:
my_sq(4)

16

In [14]:
def avg_2(x, y):
    return (x + y) / 2

In [15]:
avg_2(10, 20)

15.0

In [16]:
assert avg_2(10, 20) == 15.0

In [18]:
import pandas as pd

In [20]:
df=pd.DataFrame({'a':[10,20,30],
                 'b':[20,30,40]})
df

a   b
0  10  20
1  20  30
2  30  40

In [21]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [22]:
type(df['a'])

pandas.core.series.Series

In [29]:
def my_sq(x):
    # assert isinstance(x, int)
    return x ** 2

In [30]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [31]:
def my_exp(x, e):
    return x ** e

In [32]:
my_exp(2, 2)

4

In [33]:
my_exp(2, 10)

1024

In [36]:
df['a'].apply(my_exp, e=10)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [37]:
def print_me(x):
    print(x)

In [40]:
df

a   b
0  10  20
1  20  30
2  30  40

In [42]:
df.apply(print_me, axis=0)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [48]:
def avg_3(x, y, z):
    return (x + y + z) / 3

In [49]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [50]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z) / 3

In [51]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [52]:
import numpy as np

In [53]:
df.apply(np.mean)

a    20.0
b    30.0
dtype: float64

In [55]:
df.apply(avg_3_apply, axis=1)

IndexError: ('index out of bounds', 'occurred at index 0')

In [56]:
df

a   b
0  10  20
1  20  30
2  30  40

In [57]:
def avg_2_apply(row):
    x = row[0]
    y = row[1]
    return (x + y) / 2

In [60]:
df.apply(avg_2_apply, axis=1)

0    15.0
1    25.0
2    35.0
dtype: float64

In [61]:
import seaborn as sns

In [62]:
titanic = sns.load_dataset('titanic')

In [63]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [64]:
def count_missing(vec):
    """Counts the number of missing values in a vector
    """
    null_vec = pd.isnull(vec)
    null_count = np.sum(null_vec)
    return null_count

In [65]:
count_missing?

In [66]:
cmis_col = titanic.apply(count_missing)

In [67]:
cmis_col

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [68]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
survived       891 non-null int64
pclass         891 non-null int64
sex            891 non-null object
age            714 non-null float64
sibsp          891 non-null int64
parch          891 non-null int64
fare           891 non-null float64
embarked       889 non-null object
class          891 non-null category
who            891 non-null object
adult_male     891 non-null bool
deck           203 non-null category
embark_town    889 non-null object
alive          891 non-null object
alone          891 non-null bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [69]:
cmis_row = titanic.apply(count_missing, axis=1)

In [70]:
cmis_row

0      1
1      0
2      1
3      0
4      1
5      2
6      0
7      1
8      1
9      1
10     0
11     0
12     1
13     1
14     1
15     1
16     1
17     2
18     1
19     2
20     1
21     0
22     1
23     0
24     1
25     1
26     2
27     0
28     2
29     2
      ..
861    1
862    0
863    2
864    1
865    1
866    1
867    0
868    2
869    1
870    1
871    0
872    0
873    1
874    1
875    1
876    1
877    1
878    2
879    0
880    1
881    1
882    1
883    1
884    1
885    1
886    1
887    0
888    2
889    0
890    1
Length: 891, dtype: int64

In [71]:
def avg_2(x, y):
    return (x + y) / 2

In [72]:
df

a   b
0  10  20
1  20  30
2  30  40

In [73]:
avg_2(df['a'], df['b'])

0    15.0
1    25.0
2    35.0
dtype: float64

In [74]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [75]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [76]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [80]:
avg_2_mod(10, 20)

15.0

In [81]:
avg_2_mod(20, 30)

nan

In [82]:
import numpy as np

In [83]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [85]:
df

a   b
0  10  20
1  20  30
2  30  40

In [84]:
avg_2_mod_vec(df['a'], df['b'])

array([ 15.,  nan,  35.])

In [86]:
@np.vectorize
def v_avg_2_mod(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [87]:
v_avg_2_mod(df['a'], df['b'])

array([ 15.,  nan,  35.])

In [88]:
import numba

In [89]:
@numba.vectorize
def v_avg_2_mod_numba(x, y):
    if (x == 20):
        return np.NaN
    else:
        return (x + y) / 2

In [91]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([ 15.,  nan,  35.])

In [95]:
%%timeit
avg_2(df['a'], df['b'])

528 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [96]:
%%timeit
v_avg_2_mod(df['a'], df['b'])

138 µs ± 1.55 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [98]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

16.6 µs ± 288 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
